<html>
<head>
<title>verdistudios.com</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link rel="stylesheet" href="style.css">
</head>

<body bgcolor="#FFFFFF" text="#000000">
<center>
	<?php include("header.php"); ?>
  <tr>
    <td width="17%" height="241" valign=top>
 	<?php include("verdi1menu.php"); ?>
      <p>&nbsp;</p>
    </td>
    <td width="65%" height="241" valign=top>
	<blockquote>
        <p><FONT CLASS="HEADLINE"><B>Welcome to Verdi Studios</B></FONT></p>
        <p>Verdi Studios are award winning photographic studios within the east
          of London.</p>
        <table width="100%" border="0">
          <tr>
            <td width="54%" valign=top><b>Verdi Studios </b><br>
              225/227 Green Street<br>
              Forest Gate London<br>
              E7 8LL<br>
              Tel: 020 8472 8842<br>
              Fax: 020 8472 8882 <br>
            </td>
            <td width="46%" valign=top>
			   <b>Verdi Studios II</b> <br />
              663 High Road<br />
                Seven Kings<br />
                Ilford<br />
                Essex<br />
                IG3 8RA<br />
                Tel: 020 8599 0001<br />
                Fax: 020 8472 8882<br />

              </td>&nbsp;
          </tr>
        </table>
	<br/>
        <p>&nbsp;</p>
      </blockquote>
    </td>
    <td width="18%" height="241" valign=top>
     <?php include("verdi2menu.php"); ?>
    </td>
  </tr>
<?php include("footer.php"); ?>
</center>
</body>
</html>
