<table>
  [begin] 
  <tr bgcolor=[bg]> 
    <td width=269 valign=top height="141"> 
      <table border=0 width=100%>
        <tr> 
          <td> <img src="images/posticon.gif">[posted]</td>
        </tr>
      </table>
      <hr>
      <br>
      [post] </td>
    <td align=left valign=top width="41"> 
      <p>[username]<br>
        <font size=-1>[title]<br>
        [stars] </font></p>
    </td>
  </tr>
  <tr bgcolor=[bg]> 
    <td width=269 valign=top>Posts: <font size=-1>[postcount]</font> | Awards: 
      [awards] | Views [views]</td>
    <td align=left valign=top width="41">[editpost] <br>
      [pmlink] <br>
      [replylink]</td>
  </tr>
  [end] 
</table>
