1
<center>
<table width="100%" border="0" cellpadding=0 cellspacing=0>
  <tr> 
    <td valign=top bgcolor="#000000" height="531" cellspacing=1> 
      <table width="100%" border="0" height="525">
        <tr> 
          <td bgcolor="#CCCCCC" width="13%" height="14"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b>Posted 
            By:</b></font></td>
          <td bgcolor="#CCCCCC" width="87%" height="14"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"> 
            f0d </font></td>
        </tr>
        <tr> 
          <td bgcolor="#CCCCCC" height="17"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b>Subject:</b></font></td>
          <td bgcolor="#CCCCCC" height="17"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"> 
            Testing Something</font></td>
        </tr>
        <tr> 
          <td bgcolor="#CCCCCC" height="20"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b>Date:</b></font></td>
          <td bgcolor="#CCCCCC" height="20"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"> 
            Januaray 20001</font></td>
        </tr>
        <tr bgcolor="#FFFFFF"> 
          <td colspan="2" height="213" valign=top><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Blah, 
            this is just testing a new template for the way threaded looks.Blah, 
            this is just testing a new template for the way threaded looks.Blah, 
            this is just testing a new template for the way threaded looks.Blah, 
            this is just testing a new template for the way threaded looks.Blah, 
            this is just testing a new template for the way threaded looks.Blah, 
            this is just testing a new template for the way threaded looks.Blah, 
            this is just testing a new template for the way threaded looks.Blah, 
            this is just testing a new template for the way threaded looks.Blah, 
            this is just testing a new template for the way threaded looks.Blah, 
            this is just testing a new template for the way threaded looks.Blah, 
            this is just testing a new template for the way threaded looks.Blah, 
            this is just testing a new template for the way threaded looks.</font></td>
        </tr>
        <tr bgcolor="#FFFFFF"> 
          <td colspan="2" valign=top> 
            <table width="100%" border="0" height="238">
              <tr> 
                <td width="67%" bgcolor="#0099FF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b>Replies</b></font></td>
                <td valign=top align=right width="33%" height="18" bgcolor="#0099FF"><font face="Verdana, Arial, Helvetica, sans-serif" size="2"><b>Quick 
                  Reply</b></font></td>
              </tr>
              <tr>
                <td width="67%">&nbsp;</td>
                <td valign=top align=right width="33%"> 
                  <form name="form1" method="post" action="postreply.php">
                    <table width="94%" border="0">
                      <tr> 
                        <td width="21%">Username:</td>
                        <td width="79%"> 
                          <input type="text" name="u">
                        </td>
                      </tr>
                      <tr> 
                        <td width="21%">Password: </td>
                        <td width="79%"> 
                          <input type="password" name="p">
                        </td>
                      </tr>
                      <tr> 
                        <td colspan="2"> 
                          <textarea name="message" cols=40 rows=5></textarea>
                        </td>
                      </tr>
                      <tr> 
                        <td colspan="2"> 
                          <input type="submit" name="Submit" value="Post">
                        </td>
                      </tr>
                    </table>
                  </form>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
</center>