3
<table width="100%" border="0" cellspacing="1" cellpadding="2" height="114">
[begin]
  <tr bgcolor=[bg]>
    <td width="60" valign="top">[editpost]<br>
      <br>
      [pmlink]<br>
      <br>
      [replylink] </td>
    <td valign="top"> 
      <table border=0 width=100%>
        <tr> 
          <td> <img src="images/posticon.gif"> [posted] </td>
        </tr>
        <tr> 
          <td> 
            <hr width=98% noshade>
            [post] </td>
        </tr>
      </table>
    </td>
    <td width="150" align="right" valign="top">[username] <br>
      <font size=-1>[title]</font> <br>
      [stars] <br>
      <font size=-1>[postcount]</font> <br>
      <font size=-1>[awards]</font> <br>
      <font size=-1>[views]</font> <br>
      <br>
      [linkmenow] </td>
  </tr>
[end]
</table>

