8

[beginheader]
<table border=0 width=100%>
                 <tr>
                     <td bgcolor="[headerbg]" width=15>&nbsp;</td>
                     <td width="60%" bgcolor="[headerbg]">[forum]</td>
                     <td width="7%" bgcolor="[headerbg]">[posts]</td>
                     <td width="7%" bgcolor="[headerbg]">[topics]</td>
                     <td width="7%" bgcolor="[headerbg]">[views]</td>
                     <td width="19%" bgcolor="[headerbg]">[lastpost]</td>
                 </tr>
</table>
[endheader]



<table border=0>

[begingroup]
                 <tr bgcolor="[headerbg]">
                     <td align=center colspan=6>[groupname]</td>
                 </tr>
[endgroup]

[beginforum]
                <tr>
                    <td width=15 bgcolor="[headerbg]">[folderlink]</td>
                    <td bgcolor="[regbg]">[textlink]&nbsp;&nbsp;[threadedlink]
                                          <br><b> - </b> <font size=-1>[description]<br>[moderators][forumtype][rules]</font></td>
                    <td align=center bgcolor="[headerbg]">[thisposts]</td>
                    <td align=center bgcolor="[headerbg]">[thistopics]</td>
                    <td align=center bgcolor="[headerbg]">[thisviews]</td>
                    <td align=right bgcolor="[headerbg]">[lastpostdate]<br>[lastpostby]</td>
               </tr>
[endforum]

</table>