<html>
<head>
<title>verdistudios.com</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link rel="stylesheet" href="style.css">
</head>

<body background="images/background.gif" text="#000000">
<center>
	<?php include("header.php"); ?>
  <tr>
    <td width="120" height="241" valign=top>
 	<?php include("verdi1menu.php"); ?>
      <p>&nbsp;</p>
    </td>
      <td width="620" height="241" valign=top>
      <p><font class="HEADLINE"><b>Contact</b></font></p>
      <a href="contact_email.php">Email (kv@pverdi.demon.co.uk)</a><br />
      <a href="http://www.verdistudios.com">http://www.verdistudios.com</a><br /><br />
      <b>Verdi Studios </b><br />
      225/227 Green Street<br />
      Forest Gate London<br />
      E7 8LL<br />
      Tel: 020 8472 8842<br />
      Fax: 020 8472 8882 <br />
      <br />
      <b>Verdi Studios II</b> <br />
      663 High Road<br />
      Seven Kings<br />
      Ilford<br />
      Essex<br />
      IG3 8RA<br />
      Tel: 020 8599 0001<br />
      Fax: 020 8472 8882<br />

    </td>
    <td width="120" height="241" valign=top>
     <?php include("verdi2menu.php"); ?>
    </td>
  </tr>
<?php include("footer.php"); ?>
</center>
</body>
</html>
