<a href="index.php"><img src="images/Verdi.gif" alt="header" border="0"></a>
<table width="780" border="0" cellpadding="0">
  <tr>
    <td colspan="3" height="19">
      <table width="780" border="0" cellpadding="0" cellspacing="0">
      <tr> 
        <td width="25"><img src="images/curves/topleft.gif" width="25" height="19"></td>
        <td bgcolor="#1D488F" width="365">Welcome to Verdi Studios</td>
        <td bgcolor="#1D488F" width="365"><div align="right"><a href="login.php">Login</a> 
            | <a href="signup.php">Signup</a></div></td>
        <td  width="25"><img src="images/curves/topright.gif" width="25" height="19"></td>
      </tr>
    </table>
    </td>
  </tr>
